### ISSUE TITLE
AfterFeatures hook doesn't work in cucumber 2.1.0

### ISSUE THREAD

**Issue by pnakhat** [gkushang/cucumber-html-reporter#74]
Hi - I tried  using the hooks code in my project which is using cucumber v 2.1.0

    this.registerHandler('AfterFeatures', function (event, callback) {
        reporter.generate(options);
        callback();
    });
however, it gives an error that registerError is not a function. Any help will be much appreciated

**Comment by gkushang** [comment]
@pnakhat 

I have tested this with Cucumber V2.3.0. You do not need to have `this.`. For detailed example, please take a look at https://github.com/gkushang/cucumber-html-reporter/blob/9cbd8211040bafc7b64024cee3e57c5515e79d31/test/features/step_definitions/hooks.js#L9-L11 and https://github.com/gkushang/cucumber-html-reporter/blob/9cbd8211040bafc7b64024cee3e57c5515e79d31/test/features/step_definitions/hooks.js#L33 

I believe it would resolve the issue. Please reopen if you have any other feedback.

Thanks!
